# Generated by Django 5.0.2 on 2025-12-05 13:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0003_alumnos_maestros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAcademico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=200)),
                ('tipo_evento', models.CharField(choices=[('Conferencia', 'Conferencia'), ('Taller', 'Taller'), ('Seminario', 'Seminario'), ('Concurso', 'Concurso')], max_length=50)),
                ('fecha_realizacion', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('publico_objetivo', models.JSONField()),
                ('programa_educativo', models.CharField(blank=True, choices=[('Licenciatura en Ciencias de la Computación', 'Licenciatura en Ciencias de la Computación'), ('Licenciatura en Ingeniería en Tecnologías de la Información', 'Licenciatura en Ingeniería en Tecnologías de la Información'), ('Licenciatura en Ingeniería de Software', 'Licenciatura en Ingeniería de Software')], max_length=200, null=True)),
                ('descripcion_breve', models.TextField(max_length=300)),
                ('cupo_maximo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eventos_academicos',
                'ordering': ['-fecha_realizacion', '-hora_inicio'],
                'indexes': [models.Index(fields=['fecha_realizacion'], name='eventos_aca_fecha_r_0cca6b_idx'), models.Index(fields=['tipo_evento'], name='eventos_aca_tipo_ev_726356_idx'), models.Index(fields=['responsable_evento'], name='eventos_aca_respons_fef26b_idx')],
            },
        ),
    ]
